plugins {
    id 'io.btrace.extension'
    alias(libs.plugins.shadow)
}

compileJava {
    sourceCompatibility = 8
    targetCompatibility = 8
    javaCompiler = javaToolchains.compilerFor {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

btraceExtension {
    id = 'btrace-statsd'
    name = 'BTrace StatsD'
    description = 'StatsD metrics client for BTrace'
    services = ['io.btrace.statsd.Statsd']
}

dependencies {
    apiCompileOnly project(':btrace-core')
    implImplementation project(':btrace-core')
    implementation libs.slf4j
    testImplementation libs.junit.jupiter
}

test {
    useJUnitPlatform()
}
