plugins {
    id 'org.openjdk.btrace.extension'
    alias(libs.plugins.shadow)
}

java {
    sourceCompatibility = 8
    targetCompatibility = 8
}

compileJava {
    javaCompiler = javaToolchains.compilerFor {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

btraceExtension {
    id = 'btrace-statsd'
    name = 'BTrace StatsD'
    description = 'StatsD metrics client for BTrace'
    services = ['org.openjdk.btrace.statsd.Statsd']
}

dependencies {
    apiCompileOnly project(':btrace-core')
    implImplementation project(':btrace-core')
    implementation libs.slf4j
}
