buildscript { scriptHandler ->
    apply from: rootProject.file('buildSrc/shared.gradle'), to: scriptHandler
}

plugins {
    alias(libs.plugins.versioning)
    id 'jacoco'
}

dependencies {
    compileOnly project(':btrace-core')

    implementation libs.slf4j
    implementation libs.slf4j.simple

    testImplementation project(':btrace-core')
}

jacoco {
    toolVersion = "0.8.14"
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }

    // Focus on v2 protocol package
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, include: [
                '**/org/openjdk/btrace/core/comm/**/*.class'
            ])
        }))
    }
}

test {
    finalizedBy jacocoTestReport
}
