import org.openjdk.btrace.core.annotations.*;
import org.openjdk.btrace.core.extensions.Injected;
import org.openjdk.btrace.vibeguard.VibeGuardService;

import static org.openjdk.btrace.core.BTraceUtils.*;

/**
 * Runtime behavioral contracts for AI-generated code. Enforces latency
 * budgets, call rate limits, and null-safety on methods that may have
 * been generated by an LLM.
 *
 * <p>Attach to a JVM running AI-generated service code:
 * <pre>
 * btrace &lt;pid&gt; VibeGuard.java
 * </pre>
 */
@BTrace
public class VibeGuard {

  @Injected
  private static VibeGuardService guard;

  // ==================== Latency budgets ====================

  /**
   * Enforce 500ms latency budget on all methods in the AI-generated package.
   * Adjust the clazz pattern to match your project structure.
   */
  @OnMethod(
      clazz = "/com\\.myapp\\.ai\\..*/",
      method = "/.*/",
      location = @Location(Kind.RETURN))
  public static void checkAiLatency(
      @ProbeClassName String cls,
      @ProbeMethodName String method,
      @Duration long dur) {
    guard.checkLatency(Strings.strcat(cls, Strings.strcat(".", method)),
        dur, 500_000_000L);
  }

  // ==================== Null safety on return values ====================

  @OnMethod(
      clazz = "/com\\.myapp\\.ai\\..*/",
      method = "/.*/",
      location = @Location(Kind.RETURN))
  public static void checkNullReturn(
      @ProbeClassName String cls,
      @ProbeMethodName String method,
      @Return Object ret) {
    guard.checkNotNull(
        Strings.strcat(cls, Strings.strcat(".", method)), ret);
  }

  // ==================== Alert on violations ====================

  @OnTimer(10000)
  public static void checkViolations() {
    if (guard.hasViolations()) {
      println("=== VIBE GUARD ALERT ===");
      println(guard.getSummary());
    }
  }

  @OnEvent("summary")
  public static void onDemandSummary() {
    println(guard.getSummary());
  }
}
