import io.btrace.core.annotations.BTrace;
import io.btrace.core.annotations.Duration;
import io.btrace.core.annotations.Injected;
import io.btrace.core.annotations.Kind;
import io.btrace.core.annotations.Location;
import io.btrace.core.annotations.OnEvent;
import io.btrace.core.annotations.OnMethod;
import io.btrace.core.annotations.OnTimer;
import io.btrace.core.annotations.ProbeClassName;
import io.btrace.core.annotations.ProbeMethodName;
import io.btrace.core.annotations.Return;
import io.btrace.vibeguard.VibeGuardService;

import static io.btrace.core.BTraceUtils.*;

/**
 * Runtime behavioral contracts for AI-generated code. Enforces latency
 * budgets, call rate limits, and null-safety on methods that may have
 * been generated by an LLM.
 *
 * <p>Attach to a JVM running AI-generated service code:
 * <pre>
 * btrace &lt;pid&gt; VibeGuard.java
 * </pre>
 */
@BTrace
public class VibeGuard {

  @Injected
  private static VibeGuardService guard;

  // ==================== Latency budgets ====================

  /**
   * Enforce 500ms latency budget on all methods in the AI-generated package.
   * Adjust the clazz pattern to match your project structure.
   */
  @OnMethod(
      clazz = "/com\\.myapp\\.ai\\..*/",
      method = "/.*/",
      location = @Location(Kind.RETURN))
  public static void checkAiLatency(
      @ProbeClassName String cls,
      @ProbeMethodName String method,
      @Duration long dur) {
    guard.checkLatency(strcat(cls, strcat(".", method)), dur, 500_000_000L);
  }

  // ==================== Null safety on return values ====================

  @OnMethod(
      clazz = "/com\\.myapp\\.ai\\..*/",
      method = "/.*/",
      location = @Location(Kind.RETURN))
  public static void checkNullReturn(
      @ProbeClassName String cls,
      @ProbeMethodName String method,
      @Return Object ret) {
    guard.checkNotNull(strcat(cls, strcat(".", method)), ret);
  }

  // ==================== Alert on violations ====================

  @OnTimer(10000)
  public static void checkViolations() {
    if (guard.hasViolations()) {
      println("=== VIBE GUARD ALERT ===");
      println(guard.getSummary());
    }
  }

  @OnEvent("summary")
  public static void onDemandSummary() {
    println(guard.getSummary());
  }
}
