name: BTrace

url: https://btrace.io
baseurl: ""
description: Open-source tools for understanding Java applications.

source: .

github: 'btraceio'
gaaccount: 'UA-55468921-2'

disqus: 'btrace'
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-paginate

exclude: ['README.md', 'LICENSE']

#defaults:
#  -
#    scope:
#      path: ""      # empty string for all files
#      type: posts   # limit to posts
#    values:
#      is_post: true # automatically set is_post=true for all posts

theme: jekyll-theme-hacker
