plugins {
    id 'io.btrace.extension'
    alias(libs.plugins.shadow)
}

compileJava {
    sourceCompatibility = 8
    targetCompatibility = 8
    javaCompiler = javaToolchains.compilerFor {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

btraceExtension {
    id = 'btrace-hadoop-example'
    name = 'BTrace Hadoop Example'
    description = 'Example provided-style extension for Apache Hadoop'
    services = ['org.example.btrace.hadoop.api.HadoopApi']
}

dependencies {
    apiCompileOnly project(':btrace-core')
    implCompileOnly project(':btrace-core')
}
