plugins {
    id 'java-library'
}

compileJava {
    sourceCompatibility = 8
    targetCompatibility = 8
    javaCompiler = javaToolchains.compilerFor {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

jar {
    manifest {
        attributes(
            'Premain-Class': 'io.btrace.boot.Loader',
            'Agent-Class': 'io.btrace.boot.Loader',
            'Main-Class': 'io.btrace.boot.Loader',
            'Can-Redefine-Classes': true,
            'Can-Retransform-Classes': true
        )
    }
}
