plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'io.btrace'
version = rootProject.version

compileJava {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

description = 'Compatibility stub for the unsupported BTrace 3.0 Maven fat-agent goal'

dependencies {
    // Maven Plugin API
    compileOnly 'org.apache.maven:maven-plugin-api:3.9.6'
    compileOnly 'org.apache.maven.plugin-tools:maven-plugin-annotations:3.11.0'

    // Testing
    testImplementation libs.junit.jupiter
    testImplementation 'org.apache.maven:maven-plugin-api:3.9.6'
}

// Process the plugin.xml to substitute version (using @token@ format to avoid Maven expression conflicts)
processResources {
    filesMatching('META-INF/maven/plugin.xml') {
        filter { line ->
            line.replace('@VERSION@', project.version.toString())
        }
    }
}

// Publishing configuration for Maven plugin
publishing {
    publications {
        mavenPlugin(MavenPublication) {
            from components.java

            pom {
                name = 'BTrace Maven Plugin'
                description = project.description
                url = 'https://github.com/btraceio/btrace'
                packaging = 'maven-plugin'

                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }

                developers {
                    developer {
                        id = 'btrace'
                        name = 'BTrace Project'
                        url = 'https://github.com/btraceio'
                    }
                }

                scm {
                    url = 'https://github.com/btraceio/btrace'
                    connection = 'scm:git:https://github.com/btraceio/btrace.git'
                    developerConnection = 'scm:git:ssh://git@github.com:btraceio/btrace.git'
                }
            }
        }
    }
}
