plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

dependencies {
    implementation project(':btrace-core')
    implementation project(':btrace-agent')
    implementation 'com.googlecode.lanterna:lanterna:3.1.5'

    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

jar {
    archiveBaseName.set('btrace-ext-cli')
    archiveVersion.set('')
    archiveClassifier.set('')
    manifest { attributes('Main-Class': 'io.btrace.extcli.Main') }
}
