plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
    }
}

dependencies {
    implementation project(':btrace-core')
    implementation project(':btrace-agent')
    implementation 'com.googlecode.lanterna:lanterna:3.1.1'
    implementation libs.slf4j
}

jar {
    archiveBaseName.set('btrace-ext-cli')
    archiveVersion.set('')
    archiveClassifier.set('')
    manifest { attributes('Main-Class': 'org.openjdk.btrace.extcli.Main') }
}
