import org.apache.tools.ant.filters.*

buildscript { scriptHandler ->
    apply from: rootProject.file('buildSrc/shared.gradle'), to: scriptHandler
}

plugins {
    alias(libs.plugins.versioning)
    alias(libs.plugins.jmh)
}

dependencies {
    implementation libs.slf4j
    implementation libs.slf4j.simple
    implementation libs.jctools
    implementation libs.asm
    implementation libs.asm.util

    jmh libs.jmh
    jmh libs.jmh.annprocess
}

jmh {
    warmupIterations = 3
    iterations = 5
    fork = 2
    threads = 1
    timeUnit = 'ms'
    def jmhIncludeProp = project.findProperty('jmhInclude')
    includes = jmhIncludeProp ? [jmhIncludeProp] : ['.*BinaryProtocol.*']
    benchmarkMode = ['avgt', 'thrpt']
}

processResources {
    filter ReplaceTokens, tokens: [
        "btrace.version": project.version,
        "hash"          : versioning.info.commit
    ]
}
