/*
 * Copyright (c) 2008, 2024, Jaroslav Bachorik <j.bachorik@btrace.io>.
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.btrace.core.extensions;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Describes metadata for a BTrace extension (package-level, optional).
 *
 * <p>Place this annotation in your API module's `package-info.java` to document the extension.
 * Manifest entries generated by the Gradle plugin remain the single source of truth.
 */
@Target(ElementType.PACKAGE)
@Retention(RetentionPolicy.RUNTIME)
public @interface ExtensionDescriptor {
  /**
   * The unique name of this extension.
   *
   * @return extension name
   */
  String name();

  /**
   * The version of this extension.
   *
   * @return version string (e.g., "1.0", "2.1.0")
   */
  String version();

  /**
   * Human-readable description of this extension.
   *
   * @return description text
   */
  String description() default "";

  /**
   * Minimum BTrace version required by this extension.
   *
   * @return minimum BTrace version (e.g., "2.1")
   */
  String minBTraceVersion() default "";

  /**
   * Other extensions that must be available for this extension to function.
   *
   * @return array of required extension classes
   */
  Class<? extends Extension>[] dependencies() default {};

  /**
   * Permissions required by this extension as a whole.
   *
   * <p>These are combined with permissions declared on individual services via {@link
   * ServiceDescriptor#permissions()} when computing the effective permission set.
   */
  Permission[] permissions() default {};
}
