package org.openjdk.btrace.core.extensions;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Container annotation for multiple {@link RequiresPermission} annotations.
 *
 * <p>This annotation is automatically generated by the Java compiler when {@link
 * RequiresPermission} is repeated on a single element. It should not be used directly.
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface RequiresPermissions {
  /**
   * Array of required permission declarations.
   *
   * @return array of RequiresPermission annotations
   */
  RequiresPermission[] value();
}
