# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ gh-actions-test ]
  pull_request:
    branches: [ gh-actions-test ]
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Store JAVA_11_HOME
      run: JAVA_PATH=$(which java) && echo "JAVA_11_HOME=${JAVA_PATH/\/bin\/java/}}" >> $GITHUB_ENV
      shell: bash
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Store JAVA_8_HOME
      run: JAVA_PATH=$(which java) && echo "JAVA_8_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      shell: bash
    - name: Set up Java 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Store JAVA_9_HOME
      run: JAVA_PATH=$(which java) && echo "JAVA_9_HOME=${JAVA_PATH/\/bin\/java/\/}" >> $GITHUB_ENV
      shell: bash
    - name: Set up Java 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Store JAVA_15_HOME
      run: JAVA_PATH=$(which java) && echo "JAVA_15_HOME=${JAVA_PATH/\/bin\//\/}" >> $GITHUB_ENV
      shell: bash
    - name: Sanity
      run: $JAVA_11_HOME/bin/java -version
      shell: bash
    - name: Checkout
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: JAVA_HOME="$JAVA_11_HOME/" ./gradlew build
    
