# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ gh-actions-test ]
  pull_request:
    branches: [ gh-actions-test ]
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Sanity
      run: echo "=== $(which java)"
      shell: bash
    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Sanity
      run: echo "=== $(which java)"
      shell: bash
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup env
      run: source config_build.sh
      shell: bash
    - name: Sanity
      run: echo "=== $JAVA_11_HOME"
      shell: bash
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
